# LocalStack Tier-2 harness — ADR-015 Phase 4.
# SEPARATE from docker-compose.yml (app runtime). Runtime separation is intentional.
# Community edition: localstack/localstack:3 (no license required).
# Usage:
#   export AWS_DEFAULT_REGION=<your-aws-region>
#   task tf:local:up && task tf:local:provision && task tf:local:assert
#   task tf:local:down

services:
  localstack:
    image: localstack/localstack:3
    container_name: dc-localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs,sns,secretsmanager,iam,sts
      DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      PERSISTENCE: 0
      DISABLE_EVENTS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ls_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 10s

networks:
  ls_net:
    driver: bridge
