#!/usr/bin/env bash
# =============================================================================
# dev-admin-bootstrap.sh — Medusa v2 first-boot admin + publishable-key setup
#
# IDEMPOTENT: re-running this script is safe. If the admin user already exists,
# the "medusa user" CLI emits an error that is caught and treated as a no-op.
# The publishable key is always regenerated; .env is always overwritten with the
# fresh pk_* value from the live DB. After `docker compose down -v`, re-running
# this script produces a fully consistent .env + DB state.
#
# Usage:
#   bash scripts/dev-admin-bootstrap.sh
#   MEDUSA_ADMIN_EMAIL=admin@example.com bash scripts/dev-admin-bootstrap.sh
#
# Environment variables (all optional — sane defaults shown):
#   MEDUSA_ADMIN_EMAIL    admin email (default: hitl@oceansoft.io)
#   MEDUSA_ADMIN_PASSWORD pre-set password; generated via openssl if not set
#   MEDUSA_BACKEND_URL    backend API base URL (default: http://localhost:9000)
#   BACKEND_CONTAINER     docker container name (default: digital-commerce-backend)
#
# Generated by: task dev:bootstrap (ADLC OS-018 fullstack-engineer)
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# ── Configuration ─────────────────────────────────────────────────────────────
EMAIL="${MEDUSA_ADMIN_EMAIL:-hitl@oceansoft.io}"
BACKEND_URL="${MEDUSA_BACKEND_URL:-http://localhost:9000}"
CONTAINER="${BACKEND_CONTAINER:-digital-commerce-backend}"
ROOT_ENV="${PROJECT_ROOT}/.env"
STOREFRONT_ENV="${PROJECT_ROOT}/apps/storefront/.env.local"

# ── Colour output ─────────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
ok()   { echo -e "${GREEN}[ok]${NC}  $*"; }
warn() { echo -e "${YELLOW}[warn]${NC} $*"; }
fail() { echo -e "${RED}[fail]${NC} $*"; exit 1; }

echo ""
echo "=== Medusa v2 first-boot bootstrap ==="
echo "    email:     $EMAIL"
echo "    backend:   $BACKEND_URL"
echo "    container: $CONTAINER"
echo ""

# NOTE: This script always creates a fresh publishable key. After `docker compose down -v`,
# the DB is wiped; re-running this script overwrites .env with a new pk_* matching the new DB.
# Idempotency is achieved by `docker exec ... medusa user` exiting cleanly when user exists,
# not by checking .env state.

# ── Step 1: Resolve or generate admin password ────────────────────────────────
if [ -f "$ROOT_ENV" ] && grep -qE '^MEDUSA_ADMIN_PASSWORD=' "$ROOT_ENV"; then
  PASSWORD=$(grep -E '^MEDUSA_ADMIN_PASSWORD=' "$ROOT_ENV" | cut -d= -f2- | tr -d '"')
  ok "Using existing MEDUSA_ADMIN_PASSWORD from .env"
elif [ -n "${MEDUSA_ADMIN_PASSWORD:-}" ]; then
  PASSWORD="$MEDUSA_ADMIN_PASSWORD"
  ok "Using MEDUSA_ADMIN_PASSWORD from environment"
else
  PASSWORD=$(openssl rand -base64 16 | tr -d '/+=' | head -c 20)
  ok "Generated new MEDUSA_ADMIN_PASSWORD (not echoed)"
fi

# ── Step 2: Write initial .env entries (password + admin email) ───────────────
mkdir -p "$(dirname "$ROOT_ENV")"
if [ ! -f "$ROOT_ENV" ]; then
  touch "$ROOT_ENV"
  ok "Created .env"
fi

# Append password and admin email only if not already present
if ! grep -qE '^MEDUSA_ADMIN_EMAIL=' "$ROOT_ENV"; then
  printf '\nMEDUSA_ADMIN_EMAIL=%s\n' "$EMAIL" >> "$ROOT_ENV"
  ok "Wrote MEDUSA_ADMIN_EMAIL to .env"
fi
if ! grep -qE '^MEDUSA_ADMIN_PASSWORD=' "$ROOT_ENV"; then
  printf 'MEDUSA_ADMIN_PASSWORD=%s\n' "$PASSWORD" >> "$ROOT_ENV"
  ok "Wrote MEDUSA_ADMIN_PASSWORD to .env (not echoed)"
fi

# ── Step 3: Verify backend is reachable ───────────────────────────────────────
echo ""
echo "--- Step 3: Verify backend health ---"
HTTP_STATUS=$(curl -sf -o /dev/null -w '%{http_code}' --max-time 10 "${BACKEND_URL}/health" || true)
if [ "$HTTP_STATUS" != "200" ]; then
  fail "Backend not healthy at ${BACKEND_URL}/health (got: ${HTTP_STATUS:-no-response}). Start with: docker compose --profile backend up -d"
fi
ok "Backend healthy at ${BACKEND_URL}/health (200)"

# ── Step 4: Create admin user (idempotent — error on exists is OK) ────────────
echo ""
echo "--- Step 4: Create admin user ---"
CREATE_OUT=$(docker exec "$CONTAINER" sh -c "cd /app/apps/backend && node_modules/.bin/medusa user --email '${EMAIL}' --password '${PASSWORD}'" 2>&1 || true)
if echo "$CREATE_OUT" | grep -qi "already exists\|duplicate\|conflict\|unique\|exists"; then
  warn "Admin user already exists (expected on re-run) — continuing"
elif echo "$CREATE_OUT" | grep -qi "error\|fail"; then
  # If it's an error we don't recognize as "user exists", show the output
  # but continue — user may have been created via another path
  warn "medusa user output (may already exist): $CREATE_OUT"
else
  ok "Admin user created: $EMAIL"
fi

# ── Step 5: Authenticate and get JWT ─────────────────────────────────────────
echo ""
echo "--- Step 5: Authenticate (Medusa v2 /auth/user/emailpass) ---"

# Use separate files for body and http_code (compatible with macOS BSD + Linux)
AUTH_BODY_FILE=$(mktemp)
AUTH_HTTP_CODE=$(curl -s -o "$AUTH_BODY_FILE" -w '%{http_code}' -X POST \
  "${BACKEND_URL}/auth/user/emailpass" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"${EMAIL}\",\"password\":\"${PASSWORD}\"}" \
  --max-time 15 || true)
AUTH_BODY=$(cat "$AUTH_BODY_FILE"); rm -f "$AUTH_BODY_FILE"

if [ "$AUTH_HTTP_CODE" = "200" ]; then
  ok "Auth endpoint: /auth/user/emailpass returned 200"
  TOKEN=$(echo "$AUTH_BODY" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token',''))" 2>/dev/null || \
          echo "$AUTH_BODY" | grep -o '"token":"[^"]*"' | head -1 | cut -d'"' -f4 || true)
  AUTH_ENDPOINT="/auth/user/emailpass"
else
  # Fallback: try Medusa v1 endpoint
  warn "v2 endpoint returned ${AUTH_HTTP_CODE} — trying v1 fallback: /admin/auth/session"
  AUTH_BODY_FILE_V1=$(mktemp)
  AUTH_HTTP_CODE=$(curl -s -o "$AUTH_BODY_FILE_V1" -w '%{http_code}' -X POST \
    "${BACKEND_URL}/admin/auth/session" \
    -H "Content-Type: application/json" \
    -c /tmp/medusa-cookies.txt \
    -d "{\"email\":\"${EMAIL}\",\"password\":\"${PASSWORD}\"}" \
    --max-time 15 || true)
  AUTH_BODY=$(cat "$AUTH_BODY_FILE_V1"); rm -f "$AUTH_BODY_FILE_V1"
  TOKEN=$(echo "$AUTH_BODY" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('access_token',''))" 2>/dev/null || true)
  AUTH_ENDPOINT="/admin/auth/session"
  if [ "$AUTH_HTTP_CODE" != "200" ]; then
    fail "Both auth endpoints failed. v2: check above; v1: HTTP ${AUTH_HTTP_CODE}. Body: $AUTH_BODY"
  fi
  ok "Auth fallback: /admin/auth/session returned 200"
fi

if [ -z "$TOKEN" ]; then
  fail "Auth succeeded (HTTP 200) but could not extract token from response. Body: $AUTH_BODY"
fi
ok "JWT token obtained (auth endpoint: $AUTH_ENDPOINT)"

# ── Step 6: Create publishable API key ────────────────────────────────────────
echo ""
echo "--- Step 6: Create publishable API key ---"

KEY_BODY_FILE=$(mktemp)
KEY_HTTP_CODE=$(curl -s -o "$KEY_BODY_FILE" -w '%{http_code}' -X POST \
  "${BACKEND_URL}/admin/api-keys" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -b /tmp/medusa-cookies.txt \
  -d '{"title":"storefront-dev","type":"publishable"}' \
  --max-time 15 || true)
KEY_BODY=$(cat "$KEY_BODY_FILE"); rm -f "$KEY_BODY_FILE"

if [ "$KEY_HTTP_CODE" != "200" ] && [ "$KEY_HTTP_CODE" != "201" ]; then
  fail "Create API key failed: HTTP ${KEY_HTTP_CODE}. Body: $KEY_BODY"
fi

PK=$(echo "$KEY_BODY" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('api_key',{}).get('token',''))" 2>/dev/null || \
     echo "$KEY_BODY" | grep -o '"token":"pk_[^"]*"' | head -1 | cut -d'"' -f4 || true)

if [ -z "$PK" ] || [[ "$PK" != pk_* ]]; then
  fail "API key creation response did not contain a pk_* token. Body: $KEY_BODY"
fi
ok "Publishable key obtained: ${PK:0:12}... (type=publishable)"

# ── Step 7: Write key to both .env files ─────────────────────────────────────
echo ""
echo "--- Step 7: Write key to .env files ---"

# Root .env (for docker-compose interpolation)
if grep -qE '^NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=' "$ROOT_ENV"; then
  # Replace existing value
  TMP_ENV=$(mktemp)
  grep -v '^NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=' "$ROOT_ENV" > "$TMP_ENV"
  printf 'NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=%s\n' "$PK" >> "$TMP_ENV"
  mv "$TMP_ENV" "$ROOT_ENV"
  ok "Updated NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY in .env"
else
  printf '\nNEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=%s\n' "$PK" >> "$ROOT_ENV"
  ok "Wrote NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY to .env"
fi

# apps/storefront/.env.local (Next.js build-time consumption)
mkdir -p "$(dirname "$STOREFRONT_ENV")"
cat > "$STOREFRONT_ENV" << EOF
# Generated by scripts/dev-admin-bootstrap.sh — do not edit manually
NEXT_PUBLIC_MEDUSA_BACKEND_URL=http://localhost:9000
NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY=${PK}
NEXT_PUBLIC_BASE_URL=http://localhost:8000
NEXT_PUBLIC_DEFAULT_REGION=us
EOF
ok "Wrote apps/storefront/.env.local (NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY + 3 other vars)"

# ── Step 8: Summary ───────────────────────────────────────────────────────────
echo ""
echo "=== Bootstrap complete ==="
echo "    admin email:      $EMAIL"
echo "    auth endpoint:    $AUTH_ENDPOINT"
echo "    publishable key:  ${PK:0:12}... (pk_* prefix confirmed)"
echo "    .env:             $ROOT_ENV"
echo "    .env.local:       $STOREFRONT_ENV"
echo ""
echo "Next: rebuild storefront to bake the key into the Next.js build:"
echo "    docker compose --profile full build storefront"
echo "    docker compose --profile full up -d storefront"
echo ""
